### ISSUE TITLE
multiarch binary

### ISSUE THREAD

**Issue by GitMensch** [noword/GDB-Windows-Binaries#1]
Would you consider adding ` --enable-targets=all` to GDB's configure? This way the binaries can also be used to debug connected ARM devices or WSL or "common" remotes running on GNU/Linux.

**Comment by noword** [comment]
https://github.com/noword/GDB-Windows-Binaries#build-config

I have used `--enable-targets=all`.
You should `set architecture arm` first, when try to remote debug a ARM process.

**Comment by GitMensch** [comment]
Thanks for the note and the binaries - all fine!
